version: '3.5'


services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: Elchin
      POSTGRES_PASSWORD: Developer_19961996
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
  eccomerce-mvc:
    image: eccomerce-mvc:latest
    container_name: eccomerce-mvc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings_PostgreSQL=Server=db;Port=5432;Database=EccomerceDb;User Id=Elchin;Password=Developer_19961996;
    ports:
      - 5000:80

volumes:
  postgres-db:
    driver: local
